// <auto-generated />
using System;
using AttendanceSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417094140_RemoveSeedData")]
    partial class RemoveSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceSystem.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeNumber = "EMP001",
                            FullName = "ישראל ישראלי",
                            IsActive = true,
                            PinHash = "$2a$11$SHm.eJ4t2U4G0ZvaOeDhy.PM8wensBstri3R8yiUHMkpZZSlPiky",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("AttendanceSystem.API.Models.ShiftLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClockInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ShiftLogs");
                });

            modelBuilder.Entity("AttendanceSystem.API.Models.ShiftPause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("PauseEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PauseStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftLogId");

                    b.ToTable("ShiftPauses");
                });

            modelBuilder.Entity("AttendanceSystem.API.Models.ShiftLog", b =>
                {
                    b.HasOne("AttendanceSystem.API.Models.Employee", "Employee")
                        .WithMany("ShiftLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceSystem.API.Models.ShiftPause", b =>
                {
                    b.HasOne("AttendanceSystem.API.Models.ShiftLog", "ShiftLog")
                        .WithMany("Pauses")
                        .HasForeignKey("ShiftLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftLog");
                });

            modelBuilder.Entity("AttendanceSystem.API.Models.Employee", b =>
                {
                    b.Navigation("ShiftLogs");
                });

            modelBuilder.Entity("AttendanceSystem.API.Models.ShiftLog", b =>
                {
                    b.Navigation("Pauses");
                });
#pragma warning restore 612, 618
        }
    }
}
